import DatabaseKit

enum SPARQLExpressionSemanticName {
    static func describe(_ expression: DatabaseKit.Expression) -> String {
        switch expression {
        case .literal: return "literal"
        case .column: return "column"
        case .variable: return "variable"
        case .parameter: return "parameter"
        case .add: return "addition"
        case .subtract: return "subtraction"
        case .multiply: return "multiplication"
        case .divide: return "division"
        case .modulo: return "modulo"
        case .negate: return "negation"
        case .equal: return "equality"
        case .notEqual: return "inequality"
        case .lessThan: return "less-than comparison"
        case .lessThanOrEqual: return "less-than-or-equal comparison"
        case .greaterThan: return "greater-than comparison"
        case .greaterThanOrEqual: return "greater-than-or-equal comparison"
        case .and: return "logical conjunction"
        case .or: return "logical disjunction"
        case .not: return "logical negation"
        case .isNull: return "null test"
        case .isNotNull: return "non-null test"
        case .bound: return "bound test"
        case .like: return "LIKE expression"
        case .regex: return "regular expression"
        case .between: return "BETWEEN expression"
        case .inList: return "IN-list expression"
        case .notInList: return "NOT-IN-list expression"
        case .inSubquery: return "IN-subquery expression"
        case .aggregate: return "aggregate"
        case .function: return "function call"
        case .caseWhen: return "CASE expression"
        case .coalesce: return "COALESCE expression"
        case .nullIf: return "NULLIF expression"
        case .cast: return "cast"
        case .triple: return "RDF triple constructor"
        case .isTriple: return "RDF triple test"
        case .subject: return "RDF subject accessor"
        case .predicate: return "RDF predicate accessor"
        case .object: return "RDF object accessor"
        case .subquery: return "scalar subquery"
        case .exists: return "EXISTS subquery"
        }
    }
}
