// RelationshipIndexKind+Maintainable.swift
// RelationshipIndex - IndexKindMaintainable extension for RelationshipIndexKind
//
// Bridges RelationshipIndexKind (database-kit) with RelationshipIndexMaintainer (database-framework).

import Foundation
import Core
import Relationship
import DatabaseEngine
import FoundationDB

// MARK: - AutoConfigurableIndexKind Extension

extension RelationshipIndexKind: AutoConfigurableIndexKind {
    /// Create a RelationshipIndexConfiguration for automatic setup
    ///
    /// Called by FDBContainer during initialization to auto-generate
    /// configurations for relationship indexes without manual setup.
    ///
    /// - Parameters:
    ///   - indexName: The index name from IndexDescriptor
    ///   - modelTypeName: The model type name that owns this index
    ///   - itemLoader: Generic item loader provided by FDBContainer
    /// - Returns: RelationshipIndexConfiguration with the item loader
    public static func createConfiguration(
        indexName: String,
        modelTypeName: String,
        itemLoader: @escaping GenericItemLoader
    ) -> any IndexConfiguration {
        RelationshipIndexConfiguration(
            indexName: indexName,
            modelTypeName: modelTypeName,
            relatedItemLoader: itemLoader
        )
    }
}

// MARK: - IndexKindMaintainable Extension

extension RelationshipIndexKind: IndexKindMaintainable {
    /// Create a RelationshipIndexMaintainer for this index kind
    ///
    /// - Important: Requires `RelationshipIndexConfiguration` to be present in configurations.
    ///   This is automatically generated by `FDBContainer` via `AutoConfigurableIndexKind`.
    /// - Throws: `RelationshipIndexError.configurationNotFound` if configuration is missing
    public func makeIndexMaintainer<Item: Persistable>(
        index: Index,
        subspace: Subspace,
        idExpression: KeyExpression,
        configurations: [any IndexConfiguration]
    ) throws -> any IndexMaintainer<Item> {
        // Look for RelationshipIndexConfiguration matching both indexName and modelTypeName
        let relationshipConfig = configurations
            .compactMap { $0 as? RelationshipIndexConfiguration }
            .first { $0.indexName == index.name && $0.modelTypeName == Item.persistableType }

        // Configuration is required - auto-generated by FDBContainer
        guard let config = relationshipConfig else {
            throw RelationshipIndexError.configurationNotFound(
                indexName: index.name,
                modelType: Item.persistableType
            )
        }

        return RelationshipIndexMaintainer<Item>(
            foreignKeyFieldName: self.foreignKeyFieldName,
            relatedTypeName: self.relatedTypeName,
            relatedFieldNames: self.relatedFieldNames,
            isToMany: self.isToMany,
            index: index,
            subspace: subspace,
            idExpression: idExpression,
            relatedItemLoader: config.relatedItemLoader
        )
    }
}
