// AutoConfigurableIndexKind.swift
// DatabaseEngine - Protocol for index kinds that support automatic configuration
//
// Enables FDBContainer to auto-generate IndexConfiguration for indexes
// that require runtime setup (e.g., RelationshipIndex needs item loader).

import Foundation
import Core
import FoundationDB

/// Type-erased loader for items by type name and ID
///
/// Used by indexes that need to load related/referenced items during maintenance.
///
/// - Parameters:
///   - typeName: Name of the type to load (e.g., "Customer")
///   - id: ID value of the item to load
///   - transaction: FDB transaction to use
/// - Returns: The loaded item as type-erased Persistable, or nil if not found
public typealias GenericItemLoader = @Sendable (
    _ typeName: String,
    _ id: any Sendable,
    _ transaction: any TransactionProtocol
) async throws -> (any Persistable)?

/// Protocol for index kinds that support automatic configuration generation
///
/// Index kinds that conform to this protocol can have their configurations
/// auto-generated by FDBContainer, removing the need for manual setup.
///
/// **Design Rationale**:
/// Some index types (e.g., RelationshipIndex) require runtime capabilities
/// like loading related items. Rather than requiring users to manually
/// configure these, FDBContainer can auto-generate configurations for
/// indexes that implement this protocol.
///
/// **Usage**:
/// ```swift
/// // In RelationshipIndex module
/// extension RelationshipIndexKind: AutoConfigurableIndexKind {
///     public static func createConfiguration(
///         indexName: String,
///         modelTypeName: String,
///         itemLoader: @escaping GenericItemLoader
///     ) -> any IndexConfiguration {
///         RelationshipIndexConfiguration(
///             indexName: indexName,
///             modelTypeName: modelTypeName,
///             relatedItemLoader: itemLoader
///         )
///     }
/// }
/// ```
public protocol AutoConfigurableIndexKind {
    /// Create a configuration for this index kind
    ///
    /// - Parameters:
    ///   - indexName: The index name
    ///   - modelTypeName: The model type name that owns this index
    ///   - itemLoader: Generic item loader provided by FDBContainer
    /// - Returns: IndexConfiguration for this index kind
    static func createConfiguration(
        indexName: String,
        modelTypeName: String,
        itemLoader: @escaping GenericItemLoader
    ) -> any IndexConfiguration
}
